name: weenie-framework-example

version: "3.9"

services:
  mysql:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: weenie
    ports:
      - 3306:3306
    volumes:
      - ./.data/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root -pdev
      start_period: 5s
      interval: 10s
      retries: 3
      timeout: 5s

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
    volumes:
      - ./.data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      interval: 10s
      retries: 3
      timeout: 5s


  example-pre-release:
    image: weenie-example:latest
    environment:
      APP_ENV: development
    command: ["pnpm", "--filter", "weenie-example", "pre-release"]
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

  example:
    image: weenie-example:latest
    ports:
      - 3000:80
    environment:
      APP_ENV: development
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      example-pre-release:
        condition: service_completed_successfully
