#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
set -e

echo
echo "Running prettier..."
npx pretty-quick --staged

if [ -z "$SKIP_TSC" ]; then
  echo
  echo "Running tsc..."
  npx tsc --noEmit
fi
