name: CI

on:
  push:
    branches:
      - current
      - v*.x
      - ci-test/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Replace node version with ${{ matrix.node-version }}
        run: |
          OUTPUT="$(jq --arg nodeVersion "${{ matrix.node-version }}" '.engines.node = $nodeVersion' package.json)"
          echo "$OUTPUT" > package.json

      - uses: wymp/devops/actions/setup-node-pnpm@v1

      - run: pnpm i && pnpm check
        name: Lint and Test
